- name: Get Secrets
  hosts: localhosts
  tasks:
    - name: Create a file
      ansible.builtin.lineinfile:
        path : /tmp/test
        line: "Username: {{lookup('hashi_vault', 'secret=common/data/common token={{vault_token}} url=https://vault.psrikanth.online:8200 validate_certs=False')}}"
        create: yes

