- name: Get Secrets
  hosts: localhost
  vars:
    ssh: "{{ lookup('hashi_vault', 'secret=common/data/common/ssh token={{vault_token}} url=https://vault.psrikanth.online:8200 validate_certs=False')}}"
  tasks:
    - name: Create credentials file
      ansible.builtin.lineinfile:
        path : secrets.json
        line: "{{ssh}}"
        create: yes

